// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyV7fnZZjp-pRvya9gcw_wH62182_W0xo',
    appId: '1:1011212456285:web:c4084fda860d1ea94958b4',
    messagingSenderId: '1011212456285',
    projectId: 'app-finanzas-650fa',
    authDomain: 'app-finanzas-650fa.firebaseapp.com',
    databaseURL: 'https://app-finanzas-650fa-default-rtdb.firebaseio.com',
    storageBucket: 'app-finanzas-650fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCba8d5zuV1pioIFHHO0Pd5-i34roZO6xE',
    appId: '1:1011212456285:android:5ecd6fbf1199a5d14958b4',
    messagingSenderId: '1011212456285',
    projectId: 'app-finanzas-650fa',
    databaseURL: 'https://app-finanzas-650fa-default-rtdb.firebaseio.com',
    storageBucket: 'app-finanzas-650fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUgQ0eWq7qhvxmwJFPMQeP8W47O2yvxLM',
    appId: '1:1011212456285:ios:afb0acc97fbb8abc4958b4',
    messagingSenderId: '1011212456285',
    projectId: 'app-finanzas-650fa',
    databaseURL: 'https://app-finanzas-650fa-default-rtdb.firebaseio.com',
    storageBucket: 'app-finanzas-650fa.appspot.com',
    iosBundleId: 'com.example.pruebaLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUgQ0eWq7qhvxmwJFPMQeP8W47O2yvxLM',
    appId: '1:1011212456285:ios:2eb2fe4b4d6331504958b4',
    messagingSenderId: '1011212456285',
    projectId: 'app-finanzas-650fa',
    databaseURL: 'https://app-finanzas-650fa-default-rtdb.firebaseio.com',
    storageBucket: 'app-finanzas-650fa.appspot.com',
    iosBundleId: 'com.example.pruebaLogin.RunnerTests',
  );
}
